#
# Makefile
#
# Version:
#     $Id: Makefile,v 1.1 2010/07/11 05:40:41 kyledewey Exp $
#
# Revisions:
#      $Log: Makefile,v $
#      Revision 1.1  2010/07/11 05:40:41  kyledewey
#      Initial revision
#
#
#
#

PACKAGE = sentinel.io.output

SOURCE = \
	Output.scala \

include $(JAVA_DEV_ROOT)/Makefile

