#
# Makefile
#
# Version:
#     $Id: Makefile,v 1.1 2011/06/03 04:10:56 kyledewey Exp kyledewey $
#
# Revisions:
#      $Log: Makefile,v $
#      Revision 1.1  2011/06/03 04:10:56  kyledewey
#      Initial revision
#
#

PACKAGE = sentinel.utils.legacy

SOURCE = \
	RuleConverter.scala \

include $(JAVA_DEV_ROOT)/Makefile

