#
# Makefile
#
# Version:
#     $Id: Makefile,v 1.2 2010/06/26 04:04:04 kyledewey Exp $
#
# Revisions:
#      $Log: Makefile,v $
#      Revision 1.2  2010/06/26 04:04:04  kyledewey
#      Added Arithmetic, String, and Character.
#
#      Revision 1.1  2010/06/15 17:55:38  kyledewey
#      Initial revision
#
#
#

PACKAGE = sentinel.model.matcher

SOURCE = \
	Matcher.scala \
	Character.scala \
	Arithmetic.scala \
	String.scala \
	Database.scala \

include $(JAVA_DEV_ROOT)/Makefile


