#
# Makefile
#
# Version:
#     $Id: Makefile,v 1.1 2010/07/11 05:40:24 kyledewey Exp kyledewey $
#
# Revisions:
#      $Log: Makefile,v $
#      Revision 1.1  2010/07/11 05:40:24  kyledewey
#      Initial revision
#
#
#
#

PACKAGE = sentinel.io.input

SOURCE = \
	Input.scala \

include $(JAVA_DEV_ROOT)/Makefile

