#
# Makefile
#
# Version:
#     $Id: Makefile,v 1.2 2010/06/26 04:06:48 kyledewey Exp $
#
# Revisions:
#      $Log: Makefile,v $
#      Revision 1.2  2010/06/26 04:06:48  kyledewey
#      Added Arithmetic, Character, and String.
#
#      Revision 1.1  2010/06/15 17:56:01  kyledewey
#      Initial revision
#
#
#

PACKAGE = sentinel.model.replacer

SOURCE = \
	Replacer.scala \
	Character.scala \
	Arithmetic.scala \
	String.scala \
	Database.scala \

include $(JAVA_DEV_ROOT)/Makefile

