#
# Makefile
#
# Version:
#     $Id: Makefile,v 1.1 2010/07/11 05:57:48 kyledewey Exp kyledewey $
#
# Revisions:
#      $Log: Makefile,v $
#      Revision 1.1  2010/07/11 05:57:48  kyledewey
#      Initial revision
#
#
#
#

PACKAGE = sentinel.utils.noninteractive

SOURCE = \
	Noninteractive.scala

include $(JAVA_DEV_ROOT)/Makefile

