#
# Makefile
#
# Version:
#     $Id: Makefile,v 1.2 2011/01/30 05:31:01 kyledewey Exp kyledewey $
#
# Revisions:
#      $Log: Makefile,v $
#      Revision 1.2  2011/01/30 05:31:01  kyledewey
#      Added SentinelTree.scala.
#
#      Revision 1.1  2011/01/28 04:41:36  kyledewey
#      Initial revision
#	
#
#
#

PACKAGE = sentinel.vpl

SOURCE = \
	Node.scala \
	NodeBoard.scala \
	SentinelTree.scala \
	ComponentsTreeModel.scala \
	VisualNode.scala \
	AreaSelect.scala \
	PreFunctionParam.scala \
	Function.scala \
	Manager.scala \
	LanguageManager.scala \
	GUIFunction.scala \
	VPLInterfaces.scala \
	ComponentsTree.scala \
	DescriptionPanel.scala \
	VisualBoard.scala \
	SentinelVPL.scala \

include $(JAVA_DEV_ROOT)/Makefile

