#
# Makefile
#
# Version:
#     $Id: Makefile,v 1.1 2010/07/11 05:39:51 kyledewey Exp kyledewey $
#
# Revisions:
#      $Log: Makefile,v $
#      Revision 1.1  2010/07/11 05:39:51  kyledewey
#      Initial revision
#
#
#
#

PACKAGE = sentinel.io.input.csv

SOURCE = \
	CSV.scala \

include $(JAVA_DEV_ROOT)/Makefile

