#
# Makefile
#
# Version:
#     $Id: Makefile,v 1.1 2011/05/27 01:39:02 kyledewey Exp kyledewey $
#
# Revisions:
#      $Log: Makefile,v $
#      Revision 1.1  2011/05/27 01:39:02  kyledewey
#      Initial revision
#
#
#
#

PACKAGE = sentinel.utils.interactive

SOURCE = \
	ErrorShower.scala \
	GUIHelpers.scala \
	Parameters.scala \
	MoveableTable.scala \
	SingleSelectionTable.scala \
	ContextSensitivePopupTable.scala \
	AssociationGraph.scala \
	AssociationParameterTable.scala \
	WithReplacementSpreadsheet.scala \
	SentinelInformationPanel.scala \
	SentinelTable.scala \
	SentinelTablePanel.scala \
	ErrorSentinel.scala \

include $(JAVA_DEV_ROOT)/Makefile

