#
# Makefile
#
# Version:
#     $Id: Makefile,v 1.1 2010/06/22 22:50:50 kyledewey Exp $
#
# Revisions:
#      $Log: Makefile,v $
#      Revision 1.1  2010/06/22 22:50:50  kyledewey
#      Initial revision
#
#
#

PACKAGE = sentinel.view

SOURCE = \
	Text.scala \

include $(JAVA_DEV_ROOT)/Makefile

