#
# Makefile
#
# Version:
#     $Id: Makefile,v 1.1 2010/06/23 03:16:06 kyledewey Exp $
#
# Revisions:
#      $Log: Makefile,v $
#      Revision 1.1  2010/06/23 03:16:06  kyledewey
#      Initial revision
#
#
#

PACKAGE = sentinel.utils

SOURCE = \

include $(JAVA_DEV_ROOT)/Makefile

