#
# Makefile
#
# Version:
#     $Id: Makefile,v 1.1 2010/07/11 05:43:47 kyledewey Exp kyledewey $
#
# Revisions:
#      $Log: Makefile,v $
#      Revision 1.1  2010/07/11 05:43:47  kyledewey
#      Initial revision
#
#
#
#

PACKAGE = sentinel.io

SOURCE = \

include $(JAVA_DEV_ROOT)/Makefile

