#
# Makefile
#
# Version:
#     $Id: Makefile,v 1.1 2010/06/15 17:57:22 kyledewey Exp $
#
# Revisions:
#      $Log: Makefile,v $
#      Revision 1.1  2010/06/15 17:57:22  kyledewey
#      Initial revision
#
#
#

PACKAGE = sentinel.model.parser.xml

SOURCE = \
	ParseXML.scala \

include $(JAVA_DEV_ROOT)/Makefile


