#
# Makefile
#
# Version:
#     $Id: Makefile,v 1.1 2010/07/11 05:54:17 kyledewey Exp kyledewey $
#
# Revisions:
#      $Log: Makefile,v $
#      Revision 1.1  2010/07/11 05:54:17  kyledewey
#      Initial revision
#
#
#
#

PACKAGE = sentinel.project

SOURCE = \
	ProjectHelpers.scala \
	Project.scala \
	Parser.scala \
	Writer.scala \
	ProjectActions.scala \

include $(JAVA_DEV_ROOT)/Makefile

