#
# Makefile
#
# Version:
#     $Id: Makefile,v 1.4 2011/06/07 08:15:07 kyledewey Exp kyledewey $
#
# Revisions:
#      $Log: Makefile,v $
#      Revision 1.4  2011/06/07 08:15:07  kyledewey
#      Removed Data.scala.
#      Incorporated Data.scala into Parameters.scala.
#
#      Revision 1.3  2010/07/11 05:44:00  kyledewey
#      Added Spreadsheet.scala and ReplacerSpreadsheet.scala.
#
#      Revision 1.2  2010/06/20 17:31:35  kyledewey
#      Moved ParseTree.scala to this directory.
#
#      Revision 1.1  2010/06/15 17:55:48  kyledewey
#      Initial revision
#
#
#

PACKAGE = sentinel.model

SOURCE = \
	SentinelHelpers.scala \
	XMLHelpers.scala \
	SeqSet.scala \
	Spreadsheet.scala \
	Description.scala \
	Parameters.scala \
	Factory.scala \
	FactoryManager.scala \
	ParseTree.scala \
	InstanceResult.scala \
	ReplacerSpreadsheet.scala \

include $(JAVA_DEV_ROOT)/Makefile

