#
# Makefile
#
# Version:
#     $Id: Makefile,v 1.1 2010/06/23 03:09:25 kyledewey Exp $
#
# Revisions:
#      $Log: Makefile,v $
#      Revision 1.1  2010/06/23 03:09:25  kyledewey
#      Initial revision
#
#
#

PACKAGE = sentinel.utils.builtins

SOURCE = \
	BuiltIns.scala \

include $(JAVA_DEV_ROOT)/Makefile

