#
# Makefile
#
# Version:
#     $Id: Makefile,v 1.1 2010/06/18 03:00:12 kyledewey Exp $
#
# Revisions:
#      $Log: Makefile,v $
#      Revision 1.1  2010/06/18 03:00:12  kyledewey
#      Initial revision
#
#
#

PACKAGE = sentinel.model.writer.xml

SOURCE = \
	WriteXML.scala \

include $(JAVA_DEV_ROOT)/Makefile


